export const ADD_OR_REMOVE_FROM_FAVOURITES = 'ADD_OR_REMOVE_FROM_FAVOURITES';
export const ADD_OR_REMOVE_FROM_WISH_LIST = 'ADD_OR_REMOVE_FROM_WISH_LIST';
export const ADD_OR_REMOVE_FROM_SHOPPING_CART = 'ADD_OR_REMOVE_FROM_SHOPPING_CART';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
